runtime: python39
instance_class: F4_1G
#automatic_scaling:
#  min_instances: 50
#  min_idle_instances: 10
#  max_instances: 250
#  max_concurrent_requests: 2
#  max_pending_latency: 1s
#  target_throughput_utilization: 0.5
#default_expiration: '365d'

handlers:
  # Static assets (anything with a file extension)
  - url: /(.*\..*)
    static_files: build/\1
    upload: build/(.*)
    secure: always
    http_headers:
      X-Frame-Options: 'DENY'
      Strict-Transport-Security: 'max-age=2592000; includeSubdomains'
      X-Content-Type-Options: 'nosniff'
      X-XSS-Protection: '1; mode=block'
      Content-Security-Policy: base-uri 'none';

  # Handle all other paths by frontend
  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    expiration: '0s'
    http_headers:
      X-Frame-Options: 'DENY'
      Strict-Transport-Security: 'max-age=2592000; includeSubdomains'
      X-Content-Type-Options: 'nosniff'
      X-XSS-Protection: '1; mode=block'
      Content-Security-Policy: "
        default-src 'none';
        media-src 'self';
        img-src 'self' https: data:;
        connect-src 'self' https://*.appspot.com https://www.google-analytics.com https://www.gstatic.com/ https://*.googleapis.com;
        script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cloud.google.com https://www.googletagmanager.com https://www.google-analytics.com https://apis.google.com https://www.gstatic.com https://accounts.google.com;
        style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
        font-src 'self' https://fonts.gstatic.com;
        manifest-src 'self';
        frame-src 'self' https://accounts.google.com https://apis.google.com https://www.youtube.com https://www.youtube-nocookie.com;
      "
